

export const SIGN_UP_LOADING = 'SIGN_UP_LOADING'
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS'
export const SIGN_UP_FAILED = 'SIGN_UP_FAILED'


export const SIGN_OUT_LOADING = 'SIGN_OUT_LOADING'
export const SIGN_OUT_SUCCESS = 'SIGN_OUT_SUCCESS'
export const SIGN_OUT_FAILED = 'SIGN_OUT_FAILED'

export const SIGN_IN_LOADING = 'SING_IN_LOADING'
export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS'
export const SIGN_IN_FAILED = 'SIGN_IN_FAILED'


export const IS_USER_SIGNED_IN = 'IS_USER_SIGNED_IN'
export const IS_USER_SIGNED_OUT = 'IS_USER_SIGNED_OUT'